# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-created_at',), 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
