# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:06
from __future__ import unicode_literals

from django.db import migrations


def build_stops(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(build_stops,migrations.RunPython.noop),
    ]
