# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sheet_idx',
            field=models.IntegerField(default=0),
        ),
    ]
