# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_sample_sheet_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('trip', 'stop'), ('trip', 'index'), ('filename', 'sheet_idx', 'line_number')]),
        ),
    ]
