# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170626_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='actual_departure_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
