# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_sample_actual_departure_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='x_avg_delay_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='x_cache_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='x_max2_delay_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='x_max_delay_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
