# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171222_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='x_before_last_delay_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='x_last_delay_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
