# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20171225_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='actual_arrival_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
