# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_sample_actual_arrival_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='ignored_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
