# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-30 10:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_stop_gtfs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='hebrew_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
    ]
