# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-30 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_build_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='hebrews',
        ),
    ]
