# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-18 19:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.CharField(blank=True, max_length=50, null=True)),
                ('payloads', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), default=list, size=None)),
                ('last_save_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
