# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='current_step',
            field=models.CharField(default='welcome', max_length=50),
        ),
    ]
