# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20190318_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='approx_train_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='destination_train_station',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='source_train_station',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
