# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-27 18:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatsession_steps_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('cancel', 'cancel')], max_length=20)),
                ('full_trip', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='steps_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chatreport',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='chatbot.ChatSession'),
        ),
    ]
