# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20190527_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
