# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20190603_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
