# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 18:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20190603_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
