# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_auto_20190610_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='platform',
            field=models.CharField(choices=[('facebook', 'facebook'), ('telegram', 'telegram')], default='facebook', max_length=20),
        ),
    ]
