# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_auto_20190623_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='payloads',
        ),
    ]
