# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 12:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_remove_chatsession_payloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='payloads',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
