# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_chatsession_payloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatreport',
            name='accept_payload_index',
        ),
    ]
