# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_chatreport_real_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReportTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatreport',
            name='chat_report_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chatbot.ChatReportTrip'),
        ),
    ]
