# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_auto_20190724_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreport',
            name='wrong_report',
            field=models.BooleanField(default=False),
        ),
    ]
