# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-29 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_chatreport_wrong_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatreport',
            old_name='chat_report_trip',
            new_name='trip',
        ),
    ]
